### ISSUE TITLE
Method invocation failed because [Veeam.Backup.Core.CBackup] does not contain a method named 'GetStorages'.

### ISSUE THREAD

**Issue by AlexanderLiuckanov** [smitmartijn/public-powershell#1]
Method invocation failed because [Veeam.Backup.Core.CBackup] does not contain a method named 'GetStorages'.
At E:\install\veeamGetBackupJobSizes.ps1:24 char:3
-         $restorePoints = $job.GetStorages() | sort CreationTime -descending
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : MethodNotFound

**Comment by smitmartijn** [comment]
What Veeam B&R version are you using?

**Comment by AlexanderLiuckanov** [comment]
9

**Comment by smitmartijn** [comment]
Script was created and tested on Veeam B&R version 8. I haven't tested it on version 9 yet, so it's possible something needs to be reworked. You're welcome to fix it and put in a pull request
